use_frameworks!

target 'Autolocalizable_Example' do
  pod 'Autolocalizable', :path => '../'

  target 'Autolocalizable_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
